"""Pluggable answer generation.

Three providers behind one protocol, because the eval harness needs to compare
them and CI needs to run without either a GPU or an API key:

  extractive  no model at all. Returns the retrieved passages verbatim with
              their citations. Deterministic, free, and the baseline every
              generated answer has to beat.
  ollama      a local model (gemma4:12b by default). Free, offline, and
              reproducible on the same machine -- so the generation numbers in
              docs/ABLATION.md can be regenerated by anyone with the weights.
  anthropic   Claude via the official SDK. Best quality on Mexican legal
              Spanish; costs money, so it is opt-in.

All three return the *same* validated shape, which is what makes the harness
provider-agnostic: an answer, the note codes it used, and whether the context
was sufficient at all.
"""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass
from typing import Any, Protocol

import httpx

log = logging.getLogger(__name__)

# The contract every provider must satisfy. Enforced by JSON-schema-constrained
# decoding, not by parsing prose -- a citation extracted with a regex from free
# text is a citation you cannot trust, and the whole project is about citations
# you can trust.
ANSWER_SCHEMA: dict[str, Any] = {
    "type": "object",
    "properties": {
        "sufficient": {
            "type": "boolean",
            "description": (
                "true only if the provided excerpts contain enough information to "
                "answer. false means the answer must be a refusal."
            ),
        },
        "answer": {
            "type": "string",
            "description": "The answer in Spanish, or the reason it cannot be answered.",
        },
        "citations": {
            "type": "array",
            "items": {"type": "integer"},
            "description": "DOF note codes (codigo) actually used. Empty if sufficient=false.",
        },
    },
    "required": ["sufficient", "answer", "citations"],
    "additionalProperties": False,
}

SYSTEM = """\
Eres un asistente que responde preguntas sobre el Diario Oficial de la Federación
de México usando ÚNICAMENTE los extractos que se te proporcionan.

Reglas:
1. Cada afirmación debe provenir de un extracto. No uses conocimiento externo.
2. Cita el código de cada nota que uses en `citations`. Un código es el número
   de 7 dígitos que aparece tras "nota" en cada extracto, por ejemplo 5795170.
   Nunca uses el número de orden del extracto (1, 2, 3): un modelo pequeño
   tiende a citar la posición en vez del código, y esa respuesta se descarta.
3. Si los extractos no contienen la respuesta, pon `sufficient: false` y explica
   brevemente qué falta. NO adivines, no completes con conocimiento general y no
   respondas "probablemente". Una negativa correcta vale más que una respuesta
   plausible sin respaldo.
4. Responde en español, de forma breve y concreta.
"""


@dataclass(slots=True)
class Answer:
    sufficient: bool
    answer: str
    citations: list[int]
    provider: str = ""
    raw: str = ""

    @classmethod
    def refusal(cls, reason: str, provider: str = "") -> Answer:
        return cls(sufficient=False, answer=reason, citations=[], provider=provider)

    @classmethod
    def from_payload(cls, payload: dict[str, Any], provider: str) -> Answer:
        """Validate a provider payload. Malformed output becomes a refusal.

        A provider that returns junk must not be able to fabricate a confident
        answer -- degrading to "I don't know" is the only safe failure mode for
        a system whose whole claim is groundedness.
        """
        try:
            return cls(
                sufficient=bool(payload["sufficient"]),
                answer=str(payload["answer"]),
                citations=[int(c) for c in payload.get("citations", [])],
                provider=provider,
                raw=json.dumps(payload, ensure_ascii=False),
            )
        except (KeyError, TypeError, ValueError) as exc:
            log.warning("provider %s returned an unusable payload: %s", provider, exc)
            return cls.refusal("El modelo devolvió una respuesta inválida.", provider)


class Provider(Protocol):
    name: str

    def answer(self, question: str, context: str) -> Answer: ...


# --------------------------------------------------------------------------


class ExtractiveProvider:
    """No model. Quotes the top passages and cites them.

    The baseline. It cannot hallucinate, its citations are correct by
    construction, and it runs in CI. Any generated answer that does not beat it
    on the eval is not worth its cost -- which is the comparison the ablation
    is for.
    """

    name = "extractive"

    def __init__(self, max_passages: int = 3, chars: int = 400) -> None:
        self.max_passages = max_passages
        self.chars = chars

    def answer(self, question: str, context: str) -> Answer:
        blocks = _split_context(context)
        if not blocks:
            return Answer.refusal("No hay extractos relevantes en el corpus.", self.name)
        used = blocks[: self.max_passages]
        body = "\n\n".join(f"[nota {c}] {t[: self.chars]}" for c, t in used)
        return Answer(
            sufficient=True,
            answer=body,
            citations=[c for c, _ in used],
            provider=self.name,
        )


class OllamaProvider:
    """A local model over ollama's OpenAI-ish chat endpoint."""

    name = "ollama"

    def __init__(
        self,
        model: str = "gemma4:12b",
        host: str = "http://127.0.0.1:11434",
        timeout: float = 180.0,
    ) -> None:
        self.model = model
        self.host = host.rstrip("/")
        self.timeout = timeout
        self.name = f"ollama:{model}"

    def answer(self, question: str, context: str) -> Answer:
        payload = {
            "model": self.model,
            "stream": False,
            # gemma4 is a reasoning model: it returns a separate `thinking`
            # field and, if it spends its token budget there, `content` comes
            # back EMPTY with no error. Grounded extraction from supplied
            # passages is not a reasoning task, so we turn thinking off — it is
            # both faster and removes an entire silent-failure mode.
            "think": False,
            # ollama accepts a JSON Schema here and constrains decoding to it,
            # which gives us the same guarantee as Anthropic's structured
            # outputs without a second code path in the harness.
            "format": ANSWER_SCHEMA,
            "options": {"temperature": 0, "num_ctx": 8192},
            "messages": [
                {"role": "system", "content": SYSTEM},
                {"role": "user", "content": f"{context}\n\nPregunta: {question}"},
            ],
        }
        try:
            resp = httpx.post(f"{self.host}/api/chat", json=payload, timeout=self.timeout)
            resp.raise_for_status()
            message = resp.json()["message"]
            content = message.get("content") or ""
            if not content:
                # Empty content with a populated `thinking` field means the
                # model never got to the answer. Surfacing it as a refusal is
                # correct; silently scoring it as one would hide the cause.
                thought = (message.get("thinking") or "")[:120]
                log.warning("ollama returned no content (thinking=%r)", thought)
                return Answer.refusal("El modelo local no produjo una respuesta.", self.name)
        except (httpx.HTTPError, KeyError, ValueError) as exc:
            log.error("ollama request failed: %s", exc)
            return Answer.refusal(f"El proveedor local falló: {exc}", self.name)
        try:
            return Answer.from_payload(json.loads(content), self.name)
        except ValueError:
            return Answer.refusal("El modelo local no devolvió JSON válido.", self.name)


class AnthropicProvider:
    """Claude via the official SDK.

    Notes that are easy to get wrong and cost a 400 or a silent quality loss:

      * `temperature` / `top_p` / `top_k` are **removed** on Claude Opus 5 and
        send a 400. Determinism is not available as a knob; the JSON schema is
        what constrains the output instead.
      * Thinking is **on by default** on Opus 5 -- omitting the parameter is
        not the same as disabling it, and `max_tokens` caps thinking plus
        answer together. We keep adaptive thinking (disabling it can leak
        `<thinking>` tags into the response) and use `effort` as the cost lever.
      * `output_config.format` is the supported way to force the schema;
        assistant-turn prefills return a 400 on this model family.
    """

    name = "anthropic"

    def __init__(self, model: str = "claude-opus-5", effort: str = "low") -> None:
        self.model = model
        self.effort = effort
        self.name = f"anthropic:{model}"
        try:
            import anthropic
        except ImportError as exc:  # pragma: no cover - optional extra
            raise RuntimeError(
                "The anthropic provider needs the optional extra: uv sync --extra anthropic"
            ) from exc
        self._client = anthropic.Anthropic()

    def answer(self, question: str, context: str) -> Answer:
        import anthropic

        try:
            resp = self._client.messages.create(
                model=self.model,
                max_tokens=4096,
                system=SYSTEM,
                # Grounded extraction is not a reasoning-heavy task; `low`
                # keeps latency and spend down. Raise it if the eval says so --
                # that is exactly what the ablation measures.
                output_config={
                    "effort": self.effort,
                    "format": {"type": "json_schema", "schema": ANSWER_SCHEMA},
                },
                messages=[{"role": "user", "content": f"{context}\n\nPregunta: {question}"}],
            )
        except anthropic.APIError as exc:
            log.error("anthropic request failed: %s", exc)
            return Answer.refusal(f"La API falló: {exc}", self.name)

        # Safety classifiers can decline a request: HTTP 200 with
        # stop_reason="refusal" and no content. Reading content[0] first would
        # raise IndexError on an otherwise successful response.
        if resp.stop_reason == "refusal":
            return Answer.refusal(
                "La API rechazó la solicitud por políticas de contenido.", self.name
            )

        text = next((b.text for b in resp.content if b.type == "text"), "")
        try:
            return Answer.from_payload(json.loads(text), self.name)
        except ValueError:
            return Answer.refusal("La API no devolvió JSON válido.", self.name)


# --------------------------------------------------------------------------


def get_provider(spec: str | None = None) -> Provider:
    """Resolve a provider from a spec string or the environment.

    Default is `extractive` on purpose: the system must be runnable, testable,
    and evaluable with no model at all. Generation is an upgrade, not a
    prerequisite.
    """
    spec = spec or os.environ.get("DOF_QA_PROVIDER", "extractive")
    kind, _, arg = spec.partition(":")
    if kind == "extractive":
        return ExtractiveProvider()
    if kind == "ollama":
        return OllamaProvider(model=arg or "gemma4:12b")
    if kind == "anthropic":
        return AnthropicProvider(model=arg or "claude-opus-5")
    raise SystemExit(
        f"unknown provider {spec!r}; use extractive | ollama[:model] | anthropic[:model]"
    )


def _split_context(context: str) -> list[tuple[int, str]]:
    """Parse the context blocks that `answer.build_context` produced."""
    out: list[tuple[int, str]] = []
    for block in context.split("\n---\n"):
        block = block.strip()
        if not block.startswith("[nota codigo="):
            continue
        head, _, body = block.partition("]")
        code = head.removeprefix("[nota codigo=").split()[0]
        if code.isdigit():
            out.append((int(code), body.strip()))
    return out
